language: node_js
node_js:
- '0.10'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install pdftk imagemagick ghostscript

install:
    - npm install

before_script:
  - npm run lint
  - npm run style

after_script:
  - npm run enforce
  - npm run coveralls
